document.writeln("<div");
document.writeln("				class=\'text-gray-400 text-uppercase px-3 px-lg-4 py-4 font-weight-bold small headings-font-family\'></div>");
document.writeln("			<ul class=\'sidebar-menu list-unstyled\'>");
document.writeln("				<li class=\'sidebar-list-item\'>");
document.writeln("				<a href=\'index.jsp\' class=\'sidebar-link text-muted active\'>");
document.writeln("				<i class=\'o-home-1 mr-3 text-gray\'></i>");
document.writeln("					<span>主页</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li class=\'sidebar-list-item\'>");
document.writeln("				<a href=\'#\' class=\'sidebar-link text-muted\' data-toggle=\'collapse\' data-target=\'#goods\' aria-expanded=\'false\' aria-controls=\'goods\'>");
document.writeln("				<i class=\'o-sales-up-1 mr-3 text-gray\'></i>");
document.writeln("					<span>商品管理</span>");
document.writeln("					</a>");
document.writeln("					<div id=\'goods\' class=\'collapse\'>");
document.writeln("						<ul");
document.writeln("							class=\'sidebar-menu list-unstyled border-left border-primary border-thick\'>");
document.writeln("							<li class=\'sidebar-list-item\'><a href=\'goods_type.jsp\'");
document.writeln("								class=\'sidebar-link text-muted pl-lg-5\'>商品类别</a></li>");
document.writeln("							<li class=\'sidebar-list-item\'><a href=\'goods_info.jsp\'");
document.writeln("								class=\'sidebar-link text-muted pl-lg-5\'>商品详情</a></li>");
document.writeln("						</ul>");
document.writeln("					</div>");
document.writeln("					");
document.writeln("				</li>");
document.writeln("				<li class=\'sidebar-list-item\'>");
document.writeln("				<a href=\'#\' class=\'sidebar-link text-muted\' data-toggle=\'collapse\' data-target=\'#orders\' aria-expanded=\'false\' aria-controls=\'orders\'>");
document.writeln("				<i class=\'o-table-content-1 mr-3 text-gray\'></i>");
document.writeln("					<span>订单管理</span>");
document.writeln("					</a>");
document.writeln("					<div id=\'orders\' class=\'collapse\'>");
document.writeln("						<ul");
document.writeln("							class=\'sidebar-menu list-unstyled border-left border-primary border-thick\'>");
document.writeln("							<li class=\'sidebar-list-item\'><a href=\'order_log.jsp\'");
document.writeln("								class=\'sidebar-link text-muted pl-lg-5\'>订单日志</a></li>");
document.writeln("							<li class=\'sidebar-list-item\'><a href=\'order_info.jsp\'");
document.writeln("								class=\'sidebar-link text-muted pl-lg-5\'>订单详情</a></li>");
document.writeln("						</ul>");
document.writeln("					</div>");
document.writeln("				</li>");
document.writeln("				<li class=\'sidebar-list-item\'>");
document.writeln("				<a href=\'user.jsp\' class=\'sidebar-link text-muted\'>");
document.writeln("				<i class=\'o-survey-1 mr-3 text-gray\'></i>");
document.writeln("					<span>会员管理</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li class=\'sidebar-list-item\'>");
document.writeln("				<a href=\'root.jsp\' class=\'sidebar-link text-muted\'>");
document.writeln("				<i class=\'o-wireframe-1 mr-3 text-gray\'></i>");
document.writeln("					<span>权限管理</span>");
document.writeln("					</a>				");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("<!--");
document.writeln("			<div");
document.writeln("				class=\'text-gray-400 text-uppercase px-3 px-lg-4 py-4 font-weight-bold small headings-font-family\'>ADMIN</div>");
document.writeln("			<ul class=\'sidebar-menu list-unstyled\'>");
document.writeln("				<li class=\'sidebar-list-item\'><a href=\'#\'");
document.writeln("					class=\'sidebar-link text-muted\'><i");
document.writeln("						class=\'o-database-1 mr-3 text-gray\'></i><span>修改密码</span></a></li>");
document.writeln("			</ul> ");
document.writeln("			<ul class=\'sidebar-menu list-unstyled\'>");
document.writeln("				<li class=\'sidebar-list-item\'><a href=\'#\'");
document.writeln("					class=\'sidebar-link text-muted\'><i");
document.writeln("						class=\'o-database-1 mr-3 text-gray\'></i><span>个人中心</span></a></li>");
document.writeln("			</ul>");
document.writeln("			-->");