document.writeln("			<div id=\'myModal\' tabindex=\'-1\' role=\'dialog\'");
document.writeln("				aria-labelledby=\'exampleModalLabel\' aria-hidden=\'true\'");
document.writeln("				class=\'modal fade text-left\'>");
document.writeln("				<div role=\'document\' class=\'modal-dialog\'>");
document.writeln("					<div class=\'modal-content\'>");
document.writeln("						<div class=\'modal-header\'>");
document.writeln("							<h4 id=\'exampleModalLabel\' class=\'modal-title\'>修改密码</h4>");
document.writeln("							<button type=\'button\' data-dismiss=\'modal\' aria-label=\'Close\'");
document.writeln("								class=\'close\'>");
document.writeln("								<span aria-hidden=\'true\'>×</span>");
document.writeln("							</button>");
document.writeln("						</div>");
document.writeln("						<div class=\'modal-body\'>");
document.writeln("							<form>");
document.writeln("								<div class=\'form-group\'>");
document.writeln("									<label>密码</label> <input type=\'password\'");
document.writeln("										placeholder=\'Input your password.\' class=\'form-control\'>");
document.writeln("								</div>");
document.writeln("								<div class=\'form-group\'>");
document.writeln("									<label>重复密码</label> <input type=\'password\'");
document.writeln("										placeholder=\'Repeat your password.\' class=\'form-control\'>");
document.writeln("								</div>");
document.writeln("								<div class=\'form-group\'>");
document.writeln("									<input type=\'submit\' value=\'保存修改\' class=\'btn btn-primary\'>");
document.writeln("								</div>");
document.writeln("							</form>");
document.writeln("						</div>");
document.writeln("						<div class=\'modal-footer\'>");
document.writeln("							<button type=\'button\' data-dismiss=\'modal\'");
document.writeln("								class=\'btn btn-secondary\'>关闭</button>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("			</div>");