document.writeln("<nav class=\'navbar navbar-expand-lg px-4 py-2 bg-white shadow\'>");
document.writeln("			<a href=\'#\' class=\'sidebar-toggler text-gray-500 mr-4 mr-lg-5 lead\'><i");
document.writeln("				class=\'fas fa-align-left\'></i></a><a href=\'index.jsp\'");
document.writeln("				class=\'navbar-brand font-weight-bold text-uppercase text-base\'>eLeaf后台管理系统</a>");
document.writeln("			<ul class=\'ml-auto d-flex align-items-center list-unstyled mb-0\'>");
document.writeln("");
document.writeln("				<li class=\'nav-item dropdown mr-3\'><a id=\'notifications\'");
document.writeln("					href=\'#\' data-toggle=\'dropdown\' aria-haspopup=\'true\'");
document.writeln("					aria-expanded=\'false\'");
document.writeln("					class=\'nav-link dropdown-toggle text-gray-400 px-1\'><i");
document.writeln("						class=\'fa fa-bell\'></i><span class=\'notification-icon\'></span></a>");
document.writeln("					<div aria-labelledby=\'notifications\' class=\'dropdown-menu\'>");
document.writeln("						<a href=\'order_info.jsp\' class=\'dropdown-item\'>");
document.writeln("							<div class=\'d-flex align-items-center\'>");
document.writeln("								<div class=\'icon icon-sm bg-blue text-white\'>");
document.writeln("									<i class=\'fas fa-envelope\'></i>");
document.writeln("								</div>");
document.writeln("								<div class=\'text ml-2\'>");
document.writeln("									<p class=\'mb-0\'>2件商品待发货</p>");
document.writeln("								</div>");
document.writeln("							</div>");
document.writeln("						</a>");
document.writeln("					</div></li>");
document.writeln("				<li class=\'nav-item dropdown ml-auto\'><a id=\'userInfo\'");
document.writeln("					href=\'http://example.com\' data-toggle=\'dropdown\'");
document.writeln("					aria-haspopup=\'true\' aria-expanded=\'false\'");
document.writeln("					class=\'nav-link dropdown-toggle\'><img src=\'img/avatar-6.jpg\'");
document.writeln("						alt=\'Mark Stephen\' style=\'max-width: 2.5rem;\'");
document.writeln("						class=\'img-fluid rounded-circle shadow\'></a>");
document.writeln("					<div aria-labelledby=\'userInfo\' class=\'dropdown-menu\'>");
document.writeln("						<a href=\'#\' class=\'dropdown-item\'><strong");
document.writeln("							class=\'d-block text-uppercase headings-font-family\'>Mark");
document.writeln("								Stephen</strong><small>普通管理员</small></a>");
document.writeln("						<div class=\'dropdown-divider\'></div>");
document.writeln("						<a href=\'#\' class=\'dropdown-item\' data-toggle=\'modal\' data-target=\'#myModal\'>修改密码</a>");
document.writeln("						<div class=\'dropdown-divider\'></div>");
document.writeln("						<a href=\'login.jsp\' class=\'dropdown-item\'>登出</a>");
document.writeln("					</div></li>");
document.writeln("			</ul>");
document.writeln("		</nav>");